spring:
  application:
    name: TasteOfSeoul
    # DB 정보
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306
    username: springdbuser
    password: springdbuser
    # JSP 경로
  mvc:
    view:
     prefix: WEB-INF/view/
     suffix: .jsp

  # mybatis의 mapper xml 위치
  # 기본적으로 resources 파일 안에 만들어줘야 함.
  # resources/mybatis/mapper/mapper.xml  이 밑에 경로
mybatis:
  mapper-locations: classpath:mybatis/mapper/mapper.xml

  # 지정한 패키지 내의 모든 클래스가 MyBatis의 매핑 파일에서 별칭을 사용하여 간단하게 참조가능
  type-aliases-package: com.example.domain

  # db의 컬럼명이 user_name 일 때 이 옵션을 키면 매핑하려는 자바클래스의 필드가 user_name 이 아니고
  # username 이더라도 자동으로 db의 컬럼 user_name 과 자동으로 매핑해줌
  # snake 표기법을 camel 표기법으로 자동 변환하여 매핑처리
  configuration:
    map-underscore-to-camel-case: true

#